//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.FlightSOAP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepatureAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalGateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepatureGateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckInTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ArrivalAirport {
            get {
                return this.ArrivalAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalAirportField, value) != true)) {
                    this.ArrivalAirportField = value;
                    this.RaisePropertyChanged("ArrivalAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DepatureAirport {
            get {
                return this.DepatureAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.DepatureAirportField, value) != true)) {
                    this.DepatureAirportField = value;
                    this.RaisePropertyChanged("DepatureAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ArrivalGate {
            get {
                return this.ArrivalGateField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalGateField, value) != true)) {
                    this.ArrivalGateField = value;
                    this.RaisePropertyChanged("ArrivalGate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DepatureGate {
            get {
                return this.DepatureGateField;
            }
            set {
                if ((object.ReferenceEquals(this.DepatureGateField, value) != true)) {
                    this.DepatureGateField = value;
                    this.RaisePropertyChanged("DepatureGate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CheckInTime {
            get {
                return this.CheckInTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckInTimeField, value) != true)) {
                    this.CheckInTimeField = value;
                    this.RaisePropertyChanged("CheckInTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FlightSOAP.FlightServiceSoap")]
    public interface FlightServiceSoap {
        
        // CODEGEN: Generating message contract since element name SelectAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll", ReplyAction="*")]
        WpfApp1.FlightSOAP.SelectAllResponse SelectAll(WpfApp1.FlightSOAP.SelectAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.SelectAllResponse> SelectAllAsync(WpfApp1.FlightSOAP.SelectAllRequest request);
        
        // CODEGEN: Generating message contract since element name PingResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        WpfApp1.FlightSOAP.PingResponse Ping(WpfApp1.FlightSOAP.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.PingResponse> PingAsync(WpfApp1.FlightSOAP.PingRequest request);
        
        // CODEGEN: Generating message contract since element name flight from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        WpfApp1.FlightSOAP.InsertResponse Insert(WpfApp1.FlightSOAP.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.InsertResponse> InsertAsync(WpfApp1.FlightSOAP.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name update from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        WpfApp1.FlightSOAP.UpdateResponse Update(WpfApp1.FlightSOAP.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.UpdateResponse> UpdateAsync(WpfApp1.FlightSOAP.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name expression from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        WpfApp1.FlightSOAP.SearchResponse Search(WpfApp1.FlightSOAP.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.SearchResponse> SearchAsync(WpfApp1.FlightSOAP.SearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.SelectAllRequestBody Body;
        
        public SelectAllRequest() {
        }
        
        public SelectAllRequest(WpfApp1.FlightSOAP.SelectAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllRequestBody {
        
        public SelectAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.SelectAllResponseBody Body;
        
        public SelectAllResponse() {
        }
        
        public SelectAllResponse(WpfApp1.FlightSOAP.SelectAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApp1.FlightSOAP.Flight[] SelectAllResult;
        
        public SelectAllResponseBody() {
        }
        
        public SelectAllResponseBody(WpfApp1.FlightSOAP.Flight[] SelectAllResult) {
            this.SelectAllResult = SelectAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.PingRequestBody Body;
        
        public PingRequest() {
        }
        
        public PingRequest(WpfApp1.FlightSOAP.PingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PingRequestBody {
        
        public PingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.PingResponseBody Body;
        
        public PingResponse() {
        }
        
        public PingResponse(WpfApp1.FlightSOAP.PingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingResult;
        
        public PingResponseBody() {
        }
        
        public PingResponseBody(string PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(WpfApp1.FlightSOAP.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApp1.FlightSOAP.Flight flight;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(WpfApp1.FlightSOAP.Flight flight) {
            this.flight = flight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(WpfApp1.FlightSOAP.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(WpfApp1.FlightSOAP.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApp1.FlightSOAP.Flight update;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(WpfApp1.FlightSOAP.Flight update) {
            this.update = update;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(WpfApp1.FlightSOAP.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(WpfApp1.FlightSOAP.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expression;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string expression) {
            this.expression = expression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfApp1.FlightSOAP.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(WpfApp1.FlightSOAP.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfApp1.FlightSOAP.Flight[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(WpfApp1.FlightSOAP.Flight[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlightServiceSoapChannel : WpfApp1.FlightSOAP.FlightServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightServiceSoapClient : System.ServiceModel.ClientBase<WpfApp1.FlightSOAP.FlightServiceSoap>, WpfApp1.FlightSOAP.FlightServiceSoap {
        
        public FlightServiceSoapClient() {
        }
        
        public FlightServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.FlightSOAP.SelectAllResponse WpfApp1.FlightSOAP.FlightServiceSoap.SelectAll(WpfApp1.FlightSOAP.SelectAllRequest request) {
            return base.Channel.SelectAll(request);
        }
        
        public WpfApp1.FlightSOAP.Flight[] SelectAll() {
            WpfApp1.FlightSOAP.SelectAllRequest inValue = new WpfApp1.FlightSOAP.SelectAllRequest();
            inValue.Body = new WpfApp1.FlightSOAP.SelectAllRequestBody();
            WpfApp1.FlightSOAP.SelectAllResponse retVal = ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).SelectAll(inValue);
            return retVal.Body.SelectAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.SelectAllResponse> WpfApp1.FlightSOAP.FlightServiceSoap.SelectAllAsync(WpfApp1.FlightSOAP.SelectAllRequest request) {
            return base.Channel.SelectAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.FlightSOAP.SelectAllResponse> SelectAllAsync() {
            WpfApp1.FlightSOAP.SelectAllRequest inValue = new WpfApp1.FlightSOAP.SelectAllRequest();
            inValue.Body = new WpfApp1.FlightSOAP.SelectAllRequestBody();
            return ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).SelectAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.FlightSOAP.PingResponse WpfApp1.FlightSOAP.FlightServiceSoap.Ping(WpfApp1.FlightSOAP.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping() {
            WpfApp1.FlightSOAP.PingRequest inValue = new WpfApp1.FlightSOAP.PingRequest();
            inValue.Body = new WpfApp1.FlightSOAP.PingRequestBody();
            WpfApp1.FlightSOAP.PingResponse retVal = ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).Ping(inValue);
            return retVal.Body.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.PingResponse> WpfApp1.FlightSOAP.FlightServiceSoap.PingAsync(WpfApp1.FlightSOAP.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.FlightSOAP.PingResponse> PingAsync() {
            WpfApp1.FlightSOAP.PingRequest inValue = new WpfApp1.FlightSOAP.PingRequest();
            inValue.Body = new WpfApp1.FlightSOAP.PingRequestBody();
            return ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).PingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.FlightSOAP.InsertResponse WpfApp1.FlightSOAP.FlightServiceSoap.Insert(WpfApp1.FlightSOAP.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(WpfApp1.FlightSOAP.Flight flight) {
            WpfApp1.FlightSOAP.InsertRequest inValue = new WpfApp1.FlightSOAP.InsertRequest();
            inValue.Body = new WpfApp1.FlightSOAP.InsertRequestBody();
            inValue.Body.flight = flight;
            WpfApp1.FlightSOAP.InsertResponse retVal = ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.InsertResponse> WpfApp1.FlightSOAP.FlightServiceSoap.InsertAsync(WpfApp1.FlightSOAP.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.FlightSOAP.InsertResponse> InsertAsync(WpfApp1.FlightSOAP.Flight flight) {
            WpfApp1.FlightSOAP.InsertRequest inValue = new WpfApp1.FlightSOAP.InsertRequest();
            inValue.Body = new WpfApp1.FlightSOAP.InsertRequestBody();
            inValue.Body.flight = flight;
            return ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.FlightSOAP.UpdateResponse WpfApp1.FlightSOAP.FlightServiceSoap.Update(WpfApp1.FlightSOAP.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(WpfApp1.FlightSOAP.Flight update1) {
            WpfApp1.FlightSOAP.UpdateRequest inValue = new WpfApp1.FlightSOAP.UpdateRequest();
            inValue.Body = new WpfApp1.FlightSOAP.UpdateRequestBody();
            inValue.Body.update = update1;
            WpfApp1.FlightSOAP.UpdateResponse retVal = ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.UpdateResponse> WpfApp1.FlightSOAP.FlightServiceSoap.UpdateAsync(WpfApp1.FlightSOAP.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.FlightSOAP.UpdateResponse> UpdateAsync(WpfApp1.FlightSOAP.Flight update) {
            WpfApp1.FlightSOAP.UpdateRequest inValue = new WpfApp1.FlightSOAP.UpdateRequest();
            inValue.Body = new WpfApp1.FlightSOAP.UpdateRequestBody();
            inValue.Body.update = update;
            return ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.FlightSOAP.SearchResponse WpfApp1.FlightSOAP.FlightServiceSoap.Search(WpfApp1.FlightSOAP.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public WpfApp1.FlightSOAP.Flight[] Search(string expression) {
            WpfApp1.FlightSOAP.SearchRequest inValue = new WpfApp1.FlightSOAP.SearchRequest();
            inValue.Body = new WpfApp1.FlightSOAP.SearchRequestBody();
            inValue.Body.expression = expression;
            WpfApp1.FlightSOAP.SearchResponse retVal = ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.FlightSOAP.SearchResponse> WpfApp1.FlightSOAP.FlightServiceSoap.SearchAsync(WpfApp1.FlightSOAP.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.FlightSOAP.SearchResponse> SearchAsync(string expression) {
            WpfApp1.FlightSOAP.SearchRequest inValue = new WpfApp1.FlightSOAP.SearchRequest();
            inValue.Body = new WpfApp1.FlightSOAP.SearchRequestBody();
            inValue.Body.expression = expression;
            return ((WpfApp1.FlightSOAP.FlightServiceSoap)(this)).SearchAsync(inValue);
        }
    }
}
